import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head />
      
      <body>
        <h1 style={{ textAlign: 'center', fontSize: '3rem',　margin: '1rem' }}>
          <a href="https://next13-experiment-next.vercel.app/">コーチングAI</a>
        </h1>
        {/* タイトルをリンク化 */}
        <nav style={{ display: 'flex', justifyContent: 'center' }}>
          <ul style={{ display: 'flex', listStyle: 'none', padding: 0 }}>
            
            <li style={{ textAlign: 'center', fontSize: '1rem', margin: '0rem' }}>
              <a href="https://next13-experiment-next.vercel.app/">Home</a>
            </li>

            {/*<li style={{ margin: '0 1rem' }}>
            <a href="http://localhost:3000/contact#">お問い合わせ</a>
            </li>*/}

          </ul>
        </nav>
        {children}
      </body>
    </html>
  )
}
